name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lint-test:
    name: Lint & test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x']
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install npm dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm test
